# Generated by Django 2.0 on 2018-03-14 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20150605_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-username']},
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='article_photos/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='large_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/large/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='original_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/original/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='small_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/small/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username.', 'invalid')], verbose_name='username'),
        ),
    ]
