# Generated by Django 2.0 on 2018-02-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_notifications', '0004_notification_template_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsetting',
            options={'ordering': ['-created']},
        ),
    ]
