# Generated by Django 2.0 on 2018-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_notifications', '0006_notification_deep_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushwooshtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
