# Generated by Django 2.0 on 2018-02-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_social_network', '0005_auto_20150605_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created']},
        ),
    ]
